# Generated by Django 4.0 on 2022-01-09 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parque',
            name='senha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parque', to='login.senha'),
        ),
        migrations.AddField(
            model_name='user',
            name='parque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='login.parque'),
        ),
        migrations.AlterField(
            model_name='senha',
            name='senha',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
