# Generated by Django 4.0 on 2022-01-09 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_parque_senha_user_parque_alter_senha_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='login.parque'),
        ),
    ]
