# Generated by Django 4.0 on 2022-01-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_parque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parque',
            name='senha',
        ),
        migrations.AddField(
            model_name='senha',
            name='parque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Senha', to='login.parque'),
        ),
    ]
