# Generated by Django 4.0 on 2022-01-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_parque_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parque',
            name='user',
        ),
        migrations.AlterField(
            model_name='parque',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='parque',
            name='estado',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='senha',
            name='Representacao',
            field=models.CharField(max_length=100, verbose_name='Representação'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
